In [69]:
import numpy as np 
import pandas as pd  
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer

In [70]:
raw_mail_data=pd.read_csv("mail_data.csv")

In [71]:
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [72]:
raw_mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [73]:
raw_mail_data.shape

(5572, 2)

In [74]:
raw_mail_data['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [75]:
mail_data=raw_mail_data.where(pd.notnull(raw_mail_data), ' ')

In [76]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [77]:
mail_data.shape

(5572, 2)

### Label Encoding
#### spam ----> 0
#### ham  -----> 1

In [78]:
mail_data.loc[mail_data['Category']=='spam', 'Category',]=0 #'Category' tells which column to update

In [79]:
mail_data.loc[mail_data['Category']=='ham','Category',]=1

In [80]:
mail_data.head()

  Category                                            Message
0        1  Go until jurong point, crazy.. Available only ...
1        1                      Ok lar... Joking wif u oni...
2        0  Free entry in 2 a wkly comp to win FA Cup fina...
3        1  U dun say so early hor... U c already then say...
4        1  Nah I don't think he goes to usf, he lives aro...

### Data and Label

In [81]:
X=mail_data['Message']
Y=mail_data['Category']

In [82]:
print(X)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [83]:
print(Y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

In [84]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.3,random_state=3)

In [85]:
print(X.shape,X_train.shape,X_test.shape)

(5572,) (3900,) (1672,)

In [86]:
# Converting Text data to Feature Vectors(Numerical) that can be used as input for Logistic Regression

### Feature Extraction

In [101]:
feature_extraction=TfidfVectorizer(min_df=1, stop_words='english', lowercase=True)

In [102]:
X_train_feature=feature_extraction.fit_transform(X_train)

In [103]:
X_test_feature=feature_extraction.transform(X_test)

#### Converting y_train and y_test to integers

In [104]:
y_train=y_train.astype('int')
y_test=y_test.astype('int')

In [91]:
print(X_train_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 30448 stored elements and shape (3900, 6896)>
  Coords	Values
  (0, 1965)	0.45020567466160955
  (0, 2489)	0.5022955611445961
  (0, 1799)	0.3212783541487352
  (0, 5509)	0.40335109063478575
  (0, 2825)	0.27449571589502497
  (0, 3086)	0.2739938546908377
  (0, 3651)	0.3587221851838313
  (1, 3003)	0.2841165834640824
  (1, 6331)	0.33272056276910283
  (1, 4271)	0.19008955732757765
  (1, 3451)	0.1449316171395763
  (1, 3534)	0.33272056276910283
  (1, 3875)	0.19423188001633226
  (1, 1153)	0.31698956000242107
  (1, 3671)	0.16295245094503386
  (1, 2058)	0.18864352312402063
  (1, 6147)	0.16521313463046028
  (1, 6)	0.33272056276910283
  (1, 6813)	0.2600994552195357
  (1, 3821)	0.2433861866561607
  (1, 4277)	0.33272056276910283
  (1, 4242)	0.25454751074340237
  (2, 2825)	0.1577537562956389
  (2, 2186)	0.30299688346739717
  (2, 4682)	0.16929598326919357
  :	:
  (3897, 2642)	0.4709615183236581
  (3897, 2080)	0.4709615183236581
  (3898, 4136)	0.2510074277476222
  (3898, 6404)	0.19744558729403666
  (3898, 2289)	0.3540965327301807
  (3898, 5644)	0.22951396229460186
  (3898, 4368)	0.30361036317197826
  (3898, 5231)	0.34076077325625154
  (3898, 6308)	0.29825497493831876
  (3898, 3587)	0.3117604480135819
  (3898, 6590)	0.3055286729595858
  (3898, 3632)	0.3140198944936123
  (3898, 2081)	0.3654387356575668
  (3899, 5787)	0.17541476811943474
  (3899, 5357)	0.15974030186984906
  (3899, 2653)	0.31542089721155364
  (3899, 5583)	0.20666240505742453
  (3899, 6626)	0.3657819848307903
  (3899, 5158)	0.4511622274843279
  (3899, 6630)	0.24828777600850763
  (3899, 312)	0.22121895406199849
  (3899, 5843)	0.29193991379910367
  (3899, 133)	0.29193991379910367
  (3899, 5846)	0.30259437800239236
  (3899, 597)	0.30259437800239236

### Training Model

#### Logistic Regression

In [92]:
model=LogisticRegression()

In [93]:
model.fit(X_train_feature,y_train)

LogisticRegression()

### Evaluation

#### Accuracy on Training Data

In [114]:
X_train_prediction=model.predict(X_train_feature)
training_accuracy=accuracy_score(y_train,X_train_prediction)
print("Training Data Accuracy: ", training_accuracy)

Training Data Accuracy:  0.9661538461538461

In [105]:
X_test_prediction=model.predict(X_test_feature)
testing_accuracy=accuracy_score(y_test,X_test_prediction)
print("Testing Data Accuracy: ", testing_accuracy)

Testing Data Accuracy:  0.9647129186602871

### Building Predictive System

In [109]:
input_mail=["Nah I don't think he goes to usf, he lives around here though"]

In [110]:
input_feature=feature_extraction.transform(input_mail)

In [112]:
input_prediction=model.predict(input_feature)

In [115]:
if input_prediction[0]==1:
    print("This mail is Ham (Not Spam)")
else:
    print("This mail is Spam")

This mail is Ham (Not Spam)